### ISSUE TITLE
ADD GPIO External MUTE control

### ISSUE THREAD

**Issue by arbore2018** [nikkov/Volumio-NanoPi-Neo#1]
Hello, I use your image and find that there is noise when the clock is switched before each song.
I want to add a GPIO control DAC to mute like the example below: 
http://tkz.hateblo.jp/entry/2018/08/29/215413,
I tried recompiling the kernel, but it doesn't boot and not work, can you help me?

**Comment by nikkov** [comment]
Sorry, I don’t have time to do it now. In future I'll planned rework image to use armbian with mainline driver and configurable I2S formats (RJ,LJ,I2S) ant other useful options, include mute.

**Comment by arbore2018** [comment]
Thank you, waiting for your good news.

**Comment by nikkov** [comment]
Information about new images and build system posted at volumio forum:
[https://forum.volumio.org/volumio-nanopi-neo-t6758-60.html#p70368](url)
